---
- name: zip log over 100M
  hosts: localhost
  become: true
  become_method: sudo
  user: centos
  tasks: 
  - name: run find command
    shell: 'find /var/log  -type f  -name "*.log" -size +100M -exec gzip -v 9 {} +'

  

  